version: '3.7'
services:

  resolver1:
    networks:
      - resolver-net
    image: resolver:v1
    environment:
      - service_name=service1
      
  resolver2:
    networks:
      - resolver-net
    image: resolver:v1
    environment:
      - service_name=service2

  resolver3:
    networks:
      - resolver-net
    image: resolver:v1
    environment:
      - service_name=service3
      
  resolver4:
    networks:
      - resolver-net
    image: resolver:v1
    environment:
      - service_name=service4      
      
networks:
  resolver-net:
